repos:
  - repo: local
    hooks:
      - id: prettier
        name: validate formatting with prettier
        language: system
        files: \.(js|json|md)$
        entry: |
          bash -c 'npm run fix:prettier "${@}"' --
        stages: [pre-commit]
  - repo: https://github.com/jmlrt/check-yamlschema
    rev: v0.0.7
    hooks:
      - id: check-yamlschema
        name: validate members yaml
        files: \.yaml$
